<html xmlns:v="urn:schemas-microsoft-com:vml"
      xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:x="urn:schemas-microsoft-com:office:excel"
      xmlns="http://www.w3.org/TR/REC-html40">

<head>
    <meta http-equiv=Content-Type content="text/html; charset=windows-1252">
    <meta name=ProgId content=Excel.Sheet>
    <meta name=Generator content="Microsoft Excel 12">
    <link rel=File-List href="Sharif_files/filelist.xml">
    <!--[if !mso]>

    <![endif]-->

</head>

<body>
<!--[if !excel]>&nbsp;&nbsp;<![endif]-->
<!--The following information was generated by Microsoft Office Excel's Publish
as Web Page wizard.-->
<!--If the same item is republished from Excel, all information between the DIV
tags will be replaced.-->
<!----------------------------->
<!--START OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD -->
<!----------------------------->

<div id="Sharif_29776" align=center x:publishsource="Excel">

    <table border=0 cellpadding=0 cellspacing=0 width=718 class=xl6529776
           style='border-collapse:collapse;table-layout:fixed;width:540pt'>
        <col class=xl6529776 width=23 style='mso-width-source:userset;mso-width-alt:
 841;width:17pt'>
        <col class=xl6529776 width=66 style='mso-width-source:userset;mso-width-alt:
 2413;width:50pt'>
        <col class=xl6529776 width=22 style='mso-width-source:userset;mso-width-alt:
 804;width:17pt'>
        <col class=xl6529776 width=44 style='mso-width-source:userset;mso-width-alt:
 1609;width:33pt'>
        <col class=xl6529776 width=248 style='mso-width-source:userset;mso-width-alt:
 9069;width:186pt'>
        <col class=xl6529776 width=96 style='mso-width-source:userset;mso-width-alt:
 3510;width:72pt'>
        <col class=xl6529776 width=29 style='mso-width-source:userset;mso-width-alt:
 1060;width:22pt'>
        <col class=xl6529776 width=26 style='mso-width-source:userset;mso-width-alt:
 950;width:20pt'>
        <col class=xl6529776 width=57 style='mso-width-source:userset;mso-width-alt:
 2084;width:43pt'>
        <col class=xl6529776 width=107 style='mso-width-source:userset;mso-width-alt:
 3913;width:80pt'>
        <tr height=20 style='height:15.0pt'>
            <td colspan=10 height=20 class=xl8929776 width=718 style='height:15.0pt;
  width:540pt'>Sharif Home Appliance Ltd.</td>
        </tr>
        <tr height=16 style='height:12.0pt'>
            <td colspan=10 height=16 class=xl9029776 style='height:12.0pt'>House#15C,
                Road#15 new, Dhanmondi, Dhaka-1206</td>
        </tr>
        <tr height=16 style='height:12.0pt'>
            <td colspan=10 height=16 class=xl9029776 style='height:12.0pt'>Phone:
                02-9124615, 02-9124615 Fax: 02-9124615</td>
        </tr>
        <tr height=16 style='height:12.0pt'>
            <td height=16 class=xl6529776 style='height:12.0pt'></td>
            <td class=xl7729776></td>
            <td class=xl7729776></td>
            <td class=xl7729776></td>
            <td align=left valign=top><!--[if gte vml 1]><v:shapetype id="_x0000_t75"
                                                                      coordsize="21600,21600" o:spt="75" o:preferrelative="t" path="m@4@5l@4@11@9@11@9@5xe"
                                                                      filled="f" stroked="f">
                    <v:stroke joinstyle="miter"/>
                    <v:formulas>
                        <v:f eqn="if lineDrawn pixelLineWidth 0"/>
                        <v:f eqn="sum @0 1 0"/>
                        <v:f eqn="sum 0 0 @1"/>
                        <v:f eqn="prod @2 1 2"/>
                        <v:f eqn="prod @3 21600 pixelWidth"/>
                        <v:f eqn="prod @3 21600 pixelHeight"/>
                        <v:f eqn="sum @0 0 1"/>
                        <v:f eqn="prod @6 1 2"/>
                        <v:f eqn="prod @7 21600 pixelWidth"/>
                        <v:f eqn="sum @8 21600 0"/>
                        <v:f eqn="prod @7 21600 pixelHeight"/>
                        <v:f eqn="sum @10 21600 0"/>
                    </v:formulas>
                    <v:path o:extrusionok="f" gradientshapeok="t" o:connecttype="rect"/>
                    <o:lock v:ext="edit" aspectratio="t"/>
                </v:shapetype><v:shape id="TextBox_x0020_1" o:spid="_x0000_s1027" type="#_x0000_t75"
                                       style='position:absolute;margin-left:100.5pt;margin-top:8.25pt;width:59.25pt;
   height:20.25pt;z-index:1;visibility:visible' o:gfxdata="UEsDBBQABgAIAAAAIQBa4xFm/gAAAOIBAAATAAAAW0NvbnRlbnRfVHlwZXNdLnhtbJSRTU/EIBCG
7yb+BzJX01I9GGNK92D1qEbXHzCBaUu2BcJg3f330v24GNfEI8y8z/sE6tV2GsVMka13Cq7LCgQ5
7Y11vYKP9VNxB4ITOoOjd6RgRwyr5vKiXu8CschpxwqGlMK9lKwHmpBLH8jlSefjhCkfYy8D6g32
JG+q6lZq7xK5VKSFAU3dUoefYxKP23x9MIk0MoiHw+LSpQBDGK3GlE3l7MyPluLYUObkfocHG/gq
a4D8tWGZnC845l7y00RrSLxiTM84ZQ1pIkvjv1ykufwbslhOXPius5rKNnKbY280n6zO0XnAQBn9
X/z7kjvB5f6Hmm8AAAD//wMAUEsDBBQABgAIAAAAIQAx3V9h0gAAAI8BAAALAAAAX3JlbHMvLnJl
bHOkkMFqwzAMhu+DvYPRvXHaQxmjTm+FXksHuwpbSUxjy1gmbd++pjBYRm876hf6PvHv9rcwqZmy
eI4G1k0LiqJl5+Ng4Ot8WH2AkoLR4cSRDNxJYN+9v+1ONGGpRzL6JKpSohgYS0mfWosdKaA0nCjW
Tc85YKljHnRCe8GB9KZttzr/ZkC3YKqjM5CPbgPqfE/V/IcdvM0s3JfGctDc996+omrH13iiuVIw
D1QMuCzPMNPc1OdAv/au/+mVERN9V/5C/Eyr9cesFzV2DwAAAP//AwBQSwMEFAAGAAgAAAAhAGQc
x+SxAgAA+gcAABAAAABkcnMvc2hhcGV4bWwueG1svFVNb9swDL0P2H8QdG+tOB9OgtrFmqK7DFux
tD9AseXEqCx5khY7+/UjJcfJsO3SFM3BkUmL74l8pG5uu1qSvTC20iqlo2tGiVC5Liq1Tenz08PV
nBLruCq41Eqk9CAsvc0+frjpCrPkKt9pQyCEskswpHTnXLOMIpvvRM3ttW6EAm+pTc0dvJptVBje
QvBaRjFjs8g2RvDC7oRw98FDMx/btXolpPzkIYKpNLoOq1zLbHITIQdc+g2w+FaW2SieT+fJdHCi
zfuNbrNxMOPyaPN75myRzAaf3+KDnxCdHlD+hxyz0WLM2L+Re7Z/IS/Y9LgFfCfkI55tSM1zo1NK
iROdk5V6gXUgo/br5tH0xL7uHw2pipTGlCheQ62e4Ps73ZERjYZvcANxHZih2mj35zwPZH1IvuxK
U/el5a8obM0rBTT5UpclAbA4mcXxFOR1SOlskiTMo/MlcCQ5+JPxeBJPKcnBP1qwyWLh2QUeGKcx
1n0W+mJOBAOl1IjceX58/8U6TMQJAuGsllXxUEn5Fjnw/SBW0pA9lymVLqT+DAUhpboUi7SQvDhh
kOa8bkALVm39IYfT+KMd7EAFerHQLSqFEsmtA0dKmf/1+T/bCimSqpdMkAl2oHUHKQL/7wJq7afB
qyUDEgY1sMA6N9sNUkVOlMBEgucGn6FeUgEgIpdQp3fG7iERXZQliOmd8QdQf36t3g6/rpQ2ff5h
jJ9kW7wcZVsGvKMUggBQCzhZigNS2sA/jJpL1dAa3oCMf/zkRlBinFxpaCCQQbh7Upo7g2oAZVq3
RiKXQvpgzaVRkBGOWi63cK8OJA3aDdglxwtWqKvnNVywv7BtsWtB3P1cdNkdiBqnkvOzCXbihOpT
fsyzn94WrP4qlJVQ7p47ju3hy/HnJeptIXHZbwAAAP//AwBQSwMEFAAGAAgAAAAhAOKvDdUlAQAA
nQEAAA8AAABkcnMvZG93bnJldi54bWxskEFPAjEQhe8m/odmTLxJa2EBkUKIEeVgTBZNjLe6nWU3
bttNW9iVX28XVC4eZ977Xud1Om91RXbofGmNgOseA4Ims6o0GwGvL8urMRAfpFGysgYFfKGH+ez8
bConyjYmxd06bEgMMX4iBRQh1BNKfVaglr5nazRRy63TMsTRbahysonhuqKcsSHVsjTxhULWeFdg
9rneagFvSWr2y8H9u9riA1s91apZroMQlxft4hZIwDaczD/0SgngQPLHrw9XqlT6gE5ArBPLxWIw
ixe31cJkhXUkT9GX+1jnuM+d1cTZRkAfSGYrAQPo5uc89xiiiw1Go+Qg/a34aNhPGNAuN9gjHal/
aM5ukujspF+aMz4e86Sj6emsw3D61dk3AAAA//8DAFBLAQItABQABgAIAAAAIQBa4xFm/gAAAOIB
AAATAAAAAAAAAAAAAAAAAAAAAABbQ29udGVudF9UeXBlc10ueG1sUEsBAi0AFAAGAAgAAAAhADHd
X2HSAAAAjwEAAAsAAAAAAAAAAAAAAAAALwEAAF9yZWxzLy5yZWxzUEsBAi0AFAAGAAgAAAAhAGQc
x+SxAgAA+gcAABAAAAAAAAAAAAAAAAAAKgIAAGRycy9zaGFwZXhtbC54bWxQSwECLQAUAAYACAAA
ACEA4q8N1SUBAACdAQAADwAAAAAAAAAAAAAAAAAJBQAAZHJzL2Rvd25yZXYueG1sUEsFBgAAAAAE
AAQA9QAAAFsGAAAAAA==
">
                    <v:imagedata src="Sharif_files/Sharif_29776_image001.png" o:title=""/>
                    <o:lock v:ext="edit" aspectratio="f"/>
                    <x:ClientData ObjectType="Pict">
                        <x:SizeWithCells/>
                        <x:CF>Bitmap</x:CF>
                        <x:AutoPict/>
                    </x:ClientData>
                </v:shape><![endif]--><![if !vml]><span style='mso-ignore:vglayout;
  position:absolute;z-index:1;margin-left:134px;margin-top:11px;width:79px;
  height:27px'><img width=79 height=27
                    src="Sharif_files/Sharif_29776_image002.gif" v:shapes="TextBox_x0020_1"></span><![endif]><span
                    style='mso-ignore:vglayout2'>
  <table cellpadding=0 cellspacing=0>
   <tr>
    <td height=16 class=xl6629776 width=248 style='height:12.0pt;width:186pt'></td>
   </tr>
  </table>
  </span></td>
            <td class=xl7729776></td>
            <td class=xl7729776></td>
            <td class=xl7729776></td>
            <td class=xl7729776></td>
            <td class=xl7729776></td>
        </tr>
        <tr class=xl7729776 height=24 style='mso-height-source:userset;height:18.0pt'>
            <td height=24 class=xl7729776 style='height:18.0pt'></td>
            <td colspan=2 class=xl8629776>Party Code:<span
                    style='mso-spacerun:yes'> </span></td>
            <td class=xl6729776>1542</td>
            <td class=xl7729776></td>
            <td class=xl6829776>Bill no.</td>
            <td class=xl7729776>:</td>
            <td class=xl7729776></td>
            <td class=xl7729776 colspan=2>HAPL-9940</td>
        </tr>
        <tr class=xl7729776 height=24 style='mso-height-source:userset;height:18.0pt'>
            <td height=24 class=xl7729776 style='height:18.0pt'></td>
            <td colspan=2 class=xl8629776>Party Name:</td>
            <td class=xl6729776 colspan=2><span style='mso-spacerun:yes'> </span>M/S.
                Panishail Electronics</td>
            <td class=xl6829776>Billing Date</td>
            <td class=xl7729776>:</td>
            <td class=xl7729776></td>
            <td class=xl7729776>04.10.17</td>
            <td class=xl7729776></td>
        </tr>
        <tr class=xl7729776 height=24 style='mso-height-source:userset;height:18.0pt'>
            <td height=24 class=xl7729776 style='height:18.0pt'></td>
            <td colspan=2 class=xl8629776>Address:<span style='mso-spacerun:yes'> </span></td>
            <td class=xl6729776 colspan=2>Panishail, Masihata, Jirani, Ashulia, Savar.</td>
            <td class=xl6829776>Delivery Date</td>
            <td class=xl7729776>:</td>
            <td class=xl7729776></td>
            <td class=xl7729776>12.10.17</td>
            <td class=xl7729776></td>
        </tr>
        <tr class=xl7729776 height=24 style='mso-height-source:userset;height:18.0pt'>
            <td height=24 class=xl7729776 style='height:18.0pt'></td>
            <td colspan=2 class=xl8629776>Phone:</td>
            <td class=xl6729776 colspan=2><span style='mso-spacerun:yes'> </span>01735
                510168</td>
            <td class=xl6829776>Region Name</td>
            <td class=xl7729776>:</td>
            <td class=xl7729776></td>
            <td class=xl7729776 colspan=2>DB-030, Mirpur</td>
        </tr>
        <tr class=xl7729776 height=24 style='mso-height-source:userset;height:18.0pt'>
            <td height=24 class=xl7729776 style='height:18.0pt'></td>
            <td colspan=4 class=xl7729776><font class="font529776">Sub:</font><font
                    class="font629776"><span style='mso-spacerun:yes'>   </span>Bill for </font><font
                    class="font529776">Sharif Kitchenware</font></td>
            <td class=xl6929776>Base Name</td>
            <td class=xl6529776>:</td>
            <td class=xl6529776></td>
            <td class=xl6529776 colspan=2>DB-034, Savar</td>
        </tr>
        <tr class=xl7029776 height=32 style='mso-height-source:userset;height:24.0pt'>
            <td height=32 class=xl7029776 style='height:24.0pt'></td>
            <td class=xl7129776>Ref:<span style='mso-spacerun:yes'>   </span>N/A</td>
            <td class=xl7129776></td>
            <td class=xl7029776></td>
            <td class=xl7029776></td>
            <td class=xl7029776></td>
            <td class=xl7029776></td>
            <td class=xl7029776></td>
            <td class=xl7029776></td>
            <td class=xl7029776></td>
        </tr>
        <tr class=xl7329776 height=39 style='mso-height-source:userset;height:29.25pt'>
            <td height=39 class=xl7229776 width=23 style='height:29.25pt;width:17pt'>SL.</td>
            <td class=xl7229776 width=66 style='border-left:none;width:50pt'>Code</td>
            <td colspan=2 class=xl8729776 width=66 style='border-left:none;width:50pt'>Size</td>
            <td class=xl7229776 width=248 style='border-left:none;width:186pt'>Name</td>
            <td class=xl7229776 width=96 style='border-left:none;width:72pt'>Design</td>
            <td colspan=2 class=xl8829776 width=55 style='border-left:none;width:42pt'>Unit
                Price</td>
            <td class=xl7229776 width=57 style='border-left:none;width:43pt'>Qty.</td>
            <td class=xl7229776 width=107 style='border-left:none;width:80pt'>Total<br>
                Taka</td>
        </tr>
        <tr height=16 style='height:12.0pt'>
            <td height=16 class=xl7429776 align=right style='height:12.0pt;border-top:
  none'>1</td>
            <td class=xl7429776 style='border-top:none;border-left:none'>GSG612S</td>
            <td colspan=2 class=xl8329776 style='border-left:none'>&nbsp;</td>
            <td class=xl7429776 style='border-top:none;border-left:none'>Gas Stove
                (Single Burner Glass Top)</td>
            <td class=xl7429776 style='border-top:none;border-left:none'>SH-GSG612S</td>
            <td colspan=2 class=xl8429776 style='border-left:none'>2050</td>
            <td class=xl7429776 align=right style='border-top:none;border-left:none'>12</td>
            <td class=xl7429776 align=right style='border-top:none;border-left:none'>24600</td>
        </tr>
        <tr height=16 style='height:12.0pt'>
            <td height=16 class=xl6529776 style='height:12.0pt'></td>
            <td class=xl6529776></td>
            <td class=xl6529776></td>
            <td class=xl6529776></td>
            <td class=xl6529776></td>
            <td class=xl6529776></td>
            <td colspan=2 class=xl8529776>Total:</td>
            <td class=xl7429776 align=right style='border-top:none;border-left:none'>12</td>
            <td class=xl7429776 align=right style='border-top:none;border-left:none'>24600</td>
        </tr>
        <tr height=16 style='height:12.0pt'>
            <td height=16 class=xl6529776 style='height:12.0pt'></td>
            <td class=xl6529776></td>
            <td class=xl6529776></td>
            <td class=xl6529776></td>
            <td class=xl6529776></td>
            <td class=xl6529776></td>
            <td colspan=3 class=xl7829776>Commission 12 % =</td>
            <td class=xl7429776 align=right style='border-top:none'>2952</td>
        </tr>
        <tr height=16 style='height:12.0pt'>
            <td height=16 class=xl6529776 style='height:12.0pt'></td>
            <td class=xl6529776></td>
            <td class=xl6529776></td>
            <td class=xl6529776></td>
            <td class=xl6529776></td>
            <td colspan=4 class=xl7929776>Net payable Amount in Tk.</td>
            <td class=xl7429776 align=right style='border-top:none'>21648</td>
        </tr>
        <tr height=16 style='height:12.0pt'>
            <td height=16 class=xl7529776 colspan=5 style='height:12.0pt'>In Word : Taka
                Twenty One Thousand Six Hundred Forty Eight Only.</td>
            <td class=xl7529776></td>
            <td class=xl7529776></td>
            <td class=xl7529776></td>
            <td class=xl6529776></td>
            <td class=xl6529776></td>
        </tr>
        <tr height=16 style='height:12.0pt'>
            <td height=16 class=xl6529776 style='height:12.0pt'></td>
            <td class=xl6529776></td>
            <td class=xl6529776></td>
            <td class=xl6529776></td>
            <td class=xl7629776>Mode of Transport:</td>
            <td colspan=5 class=xl8029776 style='border-right:.5pt solid black'>&nbsp;</td>
        </tr>
        <![if supportMisalignedColumns]>
        <tr height=0 style='display:none'>
            <td width=23 style='width:17pt'></td>
            <td width=66 style='width:50pt'></td>
            <td width=22 style='width:17pt'></td>
            <td width=44 style='width:33pt'></td>
            <td width=248 style='width:186pt'></td>
            <td width=96 style='width:72pt'></td>
            <td width=29 style='width:22pt'></td>
            <td width=26 style='width:20pt'></td>
            <td width=57 style='width:43pt'></td>
            <td width=107 style='width:80pt'></td>
        </tr>
        <![endif]>
    </table>

</div>


<!----------------------------->
<!--END OF OUTPUT FROM EXCEL PUBLISH AS WEB PAGE WIZARD-->
<!----------------------------->
</body>

</html>
